services:
  - type: web
    name: ew-tracker
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.2
    healthCheckPath: /
    autoDeploy: true

databases:
  - name: ew_db
    databaseName: ew_tracker
    user: ew_tracker_user